/* Generated by tpc version 0.6.1 */

#define IS_ERROR(action) ((action) == 0)
#define IS_ACCEPT(action) ((action) == 22)
#define IS_REDUCE(action) (0 < (action) && (action) < 8)
#define IS_SHIFT(action) (8 <= (action) && (action) < 22)
#define REDUCTION(action) (action)
#define REDUCE_GOTO(state, production) \
    (goto_table[state][production -> nonterm_type])
#define SHIFT_GOTO(action) ((action) - 8)

typedef enum
{
    TT_EOF = 0,
    TT_LPAREN,
    TT_RPAREN,
    TT_DOT,
    TT_QUOTE,
    TT_ATOM
} terminal_t;

struct production
{
    reduction_t reduction;
    int nonterm_type;
    int count;
};

static struct production productions[8] =
{
    /* 0: <START> ::= <expression> */
    { identity, 0, 1 },

    /* 1: <expression> ::= LPAREN <expression-list> RPAREN */
    { make_list, 1, 3 },

    /* 2: <expression> ::= LPAREN <expression-list> DOT <expression> RPAREN */
    { make_dot_list, 1, 5 },

    /* 3: <expression> ::= LPAREN RPAREN */
    { make_nil, 1, 2 },

    /* 4: <expression> ::= QUOTE <expression> */
    { make_quote, 1, 2 },

    /* 5: <expression> ::= ATOM */
    { identity, 1, 1 },

    /* 6: <expression-list> ::= <expression-list> <expression> */
    { extend_cons, 2, 2 },

    /* 7: <expression-list> ::= <expression> */
    { make_cons, 2, 1 }
};

#define ERR 0
#define ACC 22
#define R(x) (x)
#define S(x) (x + 8)

static unsigned int sr_table[14][6] =
{
    { ERR, S(2), ERR, ERR, S(3), S(4) },
    { ACC, ERR, ERR, ERR, ERR, ERR },
    { ERR, S(2), S(7), ERR, S(3), S(4) },
    { ERR, S(2), ERR, ERR, S(3), S(4) },
    { R(5), R(5), R(5), R(5), R(5), R(5) },
    { ERR, R(7), R(7), R(7), R(7), R(7) },
    { ERR, S(2), S(10), S(11), S(3), S(4) },
    { R(3), R(3), R(3), R(3), R(3), R(3) },
    { R(4), R(4), R(4), R(4), R(4), R(4) },
    { ERR, R(6), R(6), R(6), R(6), R(6) },
    { R(1), R(1), R(1), R(1), R(1), R(1) },
    { ERR, S(2), ERR, ERR, S(3), S(4) },
    { ERR, ERR, S(13), ERR, ERR, ERR },
    { R(2), R(2), R(2), R(2), R(2), R(2) }
};

#undef ERR
#undef R
#undef S

static unsigned int goto_table[14][3] =
{
    { 0, 1, 0 },
    { 0, 0, 0 },
    { 0, 5, 6 },
    { 0, 8, 0 },
    { 0, 0, 0 },
    { 0, 0, 0 },
    { 0, 9, 0 },
    { 0, 0, 0 },
    { 0, 0, 0 },
    { 0, 0, 0 },
    { 0, 0, 0 },
    { 0, 12, 0 },
    { 0, 0, 0 },
    { 0, 0, 0 }
};

