.TH GROUPS 5 "2002 April 25"
.ds xt \fIxtickertape\fP
.ds Xt \fIXTickertape\fP
.UC 4
.SH NAME
groups \- groups subscription file for xtickertape
.SH DESCRIPTION
The groups file consists of lines containing group subscription
expressions.  Empty lines and lines beginning with a hash (#) are
ignored.  Subscription expressions are of the form:
.TP
.B <group name>:<menu op>:<auto op>:<min time>:<max time>[:<keys>]
.TP
.B group name
is the name of the tickertape group to which the rest of the line
relates.
.TP
.B menu op
indicates whether the group should appear in the \fIgroups\fP menu.
This should be one of \fBmenu\fP or \fBno menu\fP.
.TP
.B auto op
determines whether MIME attachments are automatically viewed upon
receipt of a notification for this group.  This should be one of
\fBauto\fP or \fBmanual\fP.
.TP
.B min time
indicates the minimum number of minutes to display a notification in
this group.  This value overrides the notification's timeout value if
necessary.
.TP
.B max time
sets the maximum number of minutes to display a notification in this
group.  This value overrides the notification's timeout value if
necessary.
.TP
.B keys
is a comma-separated list of key names.  The mapping from key names to
actual keys is made in the \fIkeys\fP file.
.PP
The order in which the subscription expressions appear in the groups
file determines the order in which they will appear in the groups
menu.
.SH SEE ALSO
.BR xtickertape (1),
.BR elvin (1)
.SH AUTHORS
This page was stolen by Ted Phelps <phelps@pobox.com> from the
original tickertape man page, written by Bill Segall
<bill@segall.net>.
