.TH XTICKERTAPE 1 "1998 December 23"
.ds xt \fIxtickertape\fP
.ds Xt \fIXTickertape\fP
.UC 4
.SH NAME
xtickertape \- scrolling text chat tool
.SH SYNOPSIS
.nf
xtickertape [-e elvin-url] [--elvin=elvin-url]
            [-u user] [--user=user]
            [-D domain] [--domain=domain]
            [-G groups-file] [--groups=groups-file]
            [-U usenet-file] [--usenet=usenet-file]
            [-v] [--version]
            [-h] [--help]
.fi
.SH OPTIONS
In addition to the standard X Toolkit command-line options, \*(xt may
be invoked with the following:
.TP
.B -e \fIelvin-url\fP
.TP
.BI --elvin= elvin-url
Connect to the elvin server specified by \fIelvin-url\fP.
.TP
.B -s \fIscope\fP
.TP
.BI --scope= scope
Connect to an elvin server advertising \fIscope\fP.
.TP
.B -u \fIuser\fP
.TP
.BI --user= user
Use \fIuser\fP (in conjunction with the domain) as the default name
when sending messages.
.TP
.B -D \fIdomain\fP
.TP
.BI --domain= domain
Use \fIdomain\fP (in conjunction with the user) as the default domain
when sending messages.
.TP
.B -G \fIgroups-file\fP
.TP
.BI --groups= groups-file
Read the group subscriptions out of \fIfilename\fP.
.TP
.B -U \fIusenet-file\fP
.TP
.BI --usenet= usenet-file
Read the usenet news subscriptions out of \fIfilename\fP.
.TP
.B -v
.TP
.B --version
Print out the version of xtickertape that is being run and exit.
.TP
.B -h
.TP
.B --help
Print a usage message briefly summarizing these command-line options
and then exit.
.SH DESCRIPTION
The \*(xt application is a scrolling one-line window of event
notifications, providing you with information from many sources in a
minimum of screen space.  It provides specific support for monitoring
usenet news (see \fBusenet\fP\fI(5)\fP and incoming e-mail, and also for
sending and receiving notifications belonging to specific tickertape
groups (see \fBgroups\fP\fI(5)\fP).
.PP
Notifications contain at least four pieces of information: a group, a
user, a message and a timeout.  You can filter the information you
receive by adding (or not) entries in your \fIgroups\fP file which
match the group attribute.  The user attribute is meant to give you
some idea of who is sending the message contained in the message
attribute.  The timeout indicates how many minutes a notification
should be displayed by \*(xt.  As notifications age towards their
timeout, they fade to the background color thus providing you with
some idea of how old they are.  You may specify minimum and maximum
timeouts for a given group in your \fIgroups\fP file.  You may also
expire notifications before they timeout by clicking on them with the
right mouse button (or by placing the pointer on them and pressing
the `d' key), causing them to quickly fade out.  If you wish for a
message to go away instantly, you can delete it by pressing the `x'
key.  If you find that this isn't vindictive enough, you may kill the
the message with the 'k' key.  This not only deletes the message but
also all present and future replies to it.
.PP
In addition to these four attributes, notifications may also include
MIME attachment (typically a URL).  If they do, they will be
underlined so that you can identify them, and you may click on them
with the middle mouse button to view the attachment.  If you are so
inclined, you may specify in your \fIgroups\fP file that any
notification with an attachment sent to a given group should
automatically be displayed, thus saving you the trouble of clicking on
it.  \*(Xt invokes \fImetamail\fP in order to view attachments.  The
\fIshow-url\fP script is included in the \*(xt distribution as a
viewer for URL attachements.  We reommend that you specify it as your
\fBtext/uri-list\fP viewer and, for backwards compatibility, as your
\fBx-elvin/url\fP viewer in your .mailcap file.
.PP
The scrolling speed of the tickertape can be adjusted through a number 
of keystrokes, all of which may be adjusted by overriding the
scroller's translations.  By default, the `-' key slows the scrolling
speed and the `=' key hastens it.  Also, the ',' key scrolls the text
slightly more quickly to the left (or slightly less quickly to the
right) and the '.' key does the same except to the right.
Additionally, each number key sets the scroll speed to exactly that
speed (`0' will make the scroller stop).
.PP
The scrolling speed of the tickertape can be adjusted with the `-' and
`=' keys.  These increment and decrement the number of pixels a
message should move each time the scroller is updated (see the
\fBstepSize()\fP resource below).  Direct control of the tickertape
position may be obtained by dragging the pointer with the left mouse
button pressed.  The tickertape is capable of scrolling backwards.
.PP
To send a notification you should bring up the \fIcontrol panel\fP
window.  This is done by clicking in the \*(xt window with the left
mouse button.  The control panel allows you to compose the four
attributes and optional attachment of your notification and send it.
If you clicked on a notification scrolling across your \*(xt window,
then the control panel will be configured to reply to that message.
.PP
The control panel also allows you to tell \*(xt to re-read your
\fIgroups\fP or \fIusenet\fP files if you have changed them since you
started \*(xt from the `File' menu.  You may also exit the program
from this menu (or by pressing the `q' key in the scroller window).
At the bottom of the control panel is a history of the last thirty
notifications received.  These may be displayed either in threaded
order (with replies indented and under the original message) or in
chronological order.  The user may toggle between these two views from
the `Thread History' item on the `Options' menu.  Messages which are
displayed in a bold font have an attachment, which may be viewed by
double-clicking on the message.

.SH RESOURCES
\*(Xt understands all of the core X Toolkit and Motif resource names
and classes.  Additionally, the Scroller widget understands the
following resources:
.TP
.B "groupPixel (\fPclass\fB Pixel)"
Specifies the color to use when displaying the group attribute of a
notification. 
.TP
.B "userPixel (\fPclass\fB Pixel)"
Specifies the color to use when displaying the user attribute of a
notification.
.TP
.B "stringPixel (\fPclass\fB Pixel)"
Specifies the color to use when displaying the message attribute of a
notification.
.TP
.B "separatorPixel (\fPclass\fB Pixel)"
Specifies the color to use when displaying colon characters between
the group, user and message attributes.
.TP
.B "fadeLevels (\fPclass\fB Dimension)"
Specifies the number of gradations of color to go through as a
notification fades.  Unless you have a 24-bit color display you'll
want to keep this small as \*(xt will allocate 4 times this many
colors.
.TP
.B "frequency (\fPclass\fB Dimension)"
The number of times per second to scroll the notifications in the
scroller.  Use this in conjunction with \fIstepSize\fP (below) to
adjust the speed at which notifications are scrolled.
.TP
.B "stepSize (\fPclass\fB Dimension)"
The number of pixels to move the notifications in the scroller.  Use
this in conjunction with \fIfrequency\fP (above) to adjust the speed
at which notifications are scrolled.
.SH ACTIONS
You can also customize the keystrokes and mouse clicks which control
\*(xt.  The Scroller widget recognizes the following actions:
.TP
.B start-drag()
Records the current pointer position for reference during an ensuing
drag.  Since a drag action cancels any other action (show-menu, for
example), the pointer must move a minimum distance away from this
reference position before a drag officially begins.
.TP
.B drag()
Moves the Scroller's horizontal position to match the pointer's
motion.  This should be used in conjunction with start-drag above.
.TP
.B show-menu()
Pops up the \fIcontrol panel\fP window and uses the notification under 
the pointer (if there is one) to configure the group menu.
.TP
.B show-attachment()
Displays the attachment of the notification under the pointer.
.TP
.B expire()
Deletes the notification under the pointer by quickly fading it away.
.TP
.B delete()
Deletes a message from the scroller instantly.
.TP
.B kill()
Deletes a message and all of its responses from the scroller
instantly.
.TP
.B faster()
Increases the step size of the scroller, making messages scroll more
quickly.
.TP
.B slower()
Decreases the step size of the scroller, making message scroll more
slowly.
.PP
As an example, the left mouse button could be bound to
.B delete()
and the `m' key to
.B show-menu()
by placing the following in one's .Xdefaults file.
.TP
Tickertape.scroller.translations: #override \en\e
<Btn1Down>: delete() \en\e
.br
<Key>m: show-menu() \en
.SH ENVIRONMENT VARIABLES
If
.B TICKERDIR
exists in the environment, then \*(xt will look in the directory it
names for the files \fBgroups\fP and \fBusenet\fP.  If it is not set,
it defaults to \fB$HOME/.ticker\fP.  If no user name is specified on
the command-line then the environment variables
.B USER
and
.B LOGNAME
are consulted (in that order) before resorting to asking the operating
system directly.  Similarly, if no domain is specified on the
command-line, the
.B DOMAIN
environment variable is checked before \*(xt goes mucking about with
fully-qualified domain names.  The
.B ELVIN_URL
can be used to specify an elvin server to connect to if not specified
on the command-line.

.SH FILES
.PP
.TP
.B $TICKERDIR/groups
Specifes which tickertape groups to subscribe to.
.TP
.B $TICKERDIR/usenet
Specifies which usenet news articles to subscribe to.
.SH SEE ALSO
.BR groups (5),
.BR usenet (5),
.BR elvin (1)
.BR show-url (1),
.BR metamail (1)
.na
http://www.dstc.edu.au/Elvin
.SH BUGS
E-mail bug reports to
.BR phelps@pobox.com .
Be sure to include the word "xtickertape" somewhere in the
"Subject:" field.
.SH AUTHORS
\*(Xt was written by Ted Phelps <phelps@pobox.com>.  It was based on a 
Java program,
.BR jtickertape (1)
by Julian Boot, which is to be used on lesser platforms.  Both \*(xt
and \fIjtickertape\fP were derived from the original Python version
written by Bill Segall <bill@segall.net> with contributions from the
Reject Room.


